### ISSUE TITLE
We should switch to phpcs-fixer branch in 3.x some time.

### ISSUE THREAD

**Issue by dereuromark** [cakephp/cakephp-codesniffer#101] opened 2014-09-20 17:06 UTC
Working with the [phpcs-fixer branch](https://github.com/squizlabs/PHP_CodeSniffer/tree/phpcs-fixer) quite some time now, I think we should switch to it completely some time in the 3.x development.

It would fairly decrease the time to fix trivial CS errors, as all you need to do is to apply `-f` etc and all those issues will automatically be fixed for you - a real time safer.

A CakePHP3.0 compatible wrapper plugin for it can be seen and tested here: https://github.com/dereuromark/cakephp-codesniffer/tree/3.0#phpcs-auto-fixer

There is already a branch for it in the official CakePHP repo - just a little bit outdated at the moment:
https://github.com/cakephp/cakephp-codesniffer/tree/phpcs-fixer
It contains phpcs-fixer compatible versions of the CakePHP sniffs.

A few more current ones and extra goodies can be found in https://github.com/dereuromark/codesniffer-standards repo.

**Comment by dogmatic69** [comment] 2015-06-12 14:57
I am having the same issue as @davidyell for the last couple of weeks.

```
Fatal error: Uncaught exception 'PHP_CodeSniffer_Exception' with message 'Class PHP_CodeSniffer_CommentParser_FunctionCommentParser not found' in /usr/share/pear/PHP/CodeSniffer/Standards/CakePHP/Sniffs/Commenting/FunctionCommentSniff.php on line 17

PHP_CodeSniffer_Exception: Class PHP_CodeSniffer_CommentParser_FunctionCommentParser not found in /usr/share/pear/PHP/CodeSniffer/Standards/CakePHP/Sniffs/Commenting/FunctionCommentSniff.php on line 17

Call Stack:
    0.0002     439720   1. {main}() /usr/bin/phpcs:0
    0.0139    1754336   2. PHP_CodeSniffer_CLI->runphpcs() /usr/bin/phpcs:25
    0.0145    1812592   3. PHP_CodeSniffer_CLI->process() /usr/share/pear/PHP/CodeSniffer/CLI.php:95
    0.0258    1825096   4. PHP_CodeSniffer->initStandard() /usr/share/pear/PHP/CodeSniffer/CLI.php:830
    0.1321    1849496   5. PHP_CodeSniffer->registerSniffs() /usr/share/pear/PHP/CodeSniffer.php:560
    0.1355    2108952   6. include_once('/usr/share/pear/PHP/CodeSniffer/Standards/CakePHP/Sniffs/Commenting/FunctionCommentSniff.php') /usr/share/pear/PHP/CodeSniffer.php:1318
```

Cake 2.x

**Comment by ADmad** [comment] 2015-06-12 15:04
@dogmatic69 Unless you can track down the cause and provide a fix yourself I doubt anyone has the time to look into it.

**Comment by ADmad** [comment] 2015-06-12 15:07
@dereuromark Is your original issue still relevant? I have used phpcbf.phar with our 2.x standard to update old code and it seems to work reasonably fine.

**Comment by dereuromark** [comment] 2015-06-12 15:08
Only as additions as my branch had a few more useful sniffs. Nothing totally required, though.

**Comment by ADmad** [comment] 2015-06-12 15:11
Okay, closing then. Feel free to open a PR with additional sniffs whenever you like.

**Closed by ADmad** 2015-06-12 15:11 UTC
Labels: enhancement

**Comment by dogmatic69** [comment] 2015-06-12 15:27
turns out everything was the wrong version, some how got updated and broke.
